apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-servicemonitor
  namespace: mern-app
  labels:
    release: prometheus   # 👈 must match your kube-prometheus-stack release name
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - mern-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
